-- Auth

DROP TABLE IF EXISTS auth;
CREATE TABLE IF NOT EXISTS auth
(
    id            INTEGER PRIMARY KEY,
    user_id       INTEGER NOT NULL,
    token         TEXT,
    creation_date INTEGER DEFAULT NULL,
    FOREIGN KEY (user_id) REFERENCES user (user_id)
);

CREATE TRIGGER AutoGenerateDATETIME_auth
    AFTER INSERT
    ON auth
    FOR EACH ROW
    WHEN (NEW.creation_date IS NULL)
BEGIN
    UPDATE auth
    SET creation_date = (strftime('%s', CURRENT_TIMESTAMP))
    WHERE rowid = NEW.rowid;
END;

INSERT INTO auth (user_id, token) VALUES (1, 'adsfasdf');

SELECT * FROM auth;
