-- Message

DROP TABLE IF EXISTS message;

CREATE TABLE message
(
    message_id    INTEGER PRIMARY KEY AUTOINCREMENT,
    text          TEXT    NOT NULL,
    chat_id       INTEGER NOT NULL,
    user_id       INTEGER NOT NULL,
    creation_date INTEGER NULL,
    FOREIGN KEY (user_id) REFERENCES user (user_id)
);

CREATE TRIGGER AutoGenerateDATETIME_message
    AFTER INSERT
    ON message
    FOR EACH ROW
    WHEN (NEW.creation_date IS NULL)
BEGIN
    UPDATE message
    SET creation_date = (strftime('%s', CURRENT_TIMESTAMP))
    WHERE rowid = NEW.rowid;
END;

-- C
INSERT INTO message (text, chat_id, user_id)
VALUES ('some text', 1, 1);

-- R
SELECT *
FROM message
ORDER BY creation_date
LIMIT 10 OFFSET 0;
-- pages count (limit 10)
SELECT round((21 + (10 - 1)) / 10);

-- U
-- -

-- D
DELETE
FROM message
WHERE message_id = 13;

SELECT creation_date, datetime(creation_date, 'unixepoch') h_time FROM message;
