-- User

DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user
(
    user_id    INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name TEXT,
    last_name  TEXT,
    login      TEXT NOT NULL,
    password   TEXT NOT NULL,
    creation_date INTEGER DEFAULT NULL
);

CREATE TRIGGER AutoGenerateDATETIME_user
    AFTER INSERT
    ON user
    FOR EACH ROW
    WHEN (NEW.creation_date IS NULL)
BEGIN
    UPDATE user
    SET creation_date = (strftime('%s', CURRENT_TIMESTAMP))
    WHERE rowid = NEW.rowid;
END;

INSERT INTO user (first_name, last_name, login, password)
VALUES ('John', 'Smith', 'user', 'yHib133sIzhCU');

INSERT INTO user (first_name, last_name, login, password)
VALUES ('Mary', 'Hopkins', 'lady', 'yH0gEKEZemiTc');

-- CREATE TRIGGER AutoGenerateGUID_user
--     AFTER INSERT
--     ON user
--     FOR EACH ROW
--     WHEN (NEW.user_id IS NULL)
-- BEGIN
--     UPDATE user
--     SET user_id = (select hex(randomblob(4)) || '-' || hex(randomblob(2))
--                               || '-' || '4' || substr(hex(randomblob(2)), 2) ||
--                           '-'
--                               || substr('AB89', 1 + (abs(random()) % 4), 1) ||
--                           substr(hex(randomblob(2)), 2) || '-' ||
--                           hex(randomblob(6)))
--     WHERE rowid = NEW.rowid;
-- END;